### ISSUE TITLE
全局设置的问题

### ISSUE THREAD

**Issue by guigui0326** [642661520/layer-vue#3]
我按照示例在main.js设置默认配置zindex、skin、log，但是只有skin生效
![image](https://user-images.githubusercontent.com/30816908/135220084-6effbe41-7b99-425c-a5a8-bbe0527611cd.png)
组件的zindex依旧默认1 我尝试设置默认title 也依旧是信息

**Comment by 642661520** [comment]
全局zindex设置的是置顶窗口的初始值，请配合settop使用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Firstmeet·初见 ***@***.***&gt;
发送时间: 2021年9月29日 15:10
收件人: 642661520/layer-vue ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[642661520/layer-vue] 全局设置的问题 (#3)





 
我按照示例在main.js设置默认配置zindex、skin、log，但是只有skin生效
 
 组件的zindex依旧默认1 我尝试设置默认title 也依旧是信息
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 642661520** [comment]
设置title无效实例，请贴上代码我看下

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Firstmeet·初见 ***@***.***&gt;
发送时间: 2021年9月29日 15:10
收件人: 642661520/layer-vue ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[642661520/layer-vue] 全局设置的问题 (#3)





 
我按照示例在main.js设置默认配置zindex、skin、log，但是只有skin生效
 
 组件的zindex依旧默认1 我尝试设置默认title 也依旧是信息
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guigui0326** [comment]
配合settop可以了，感谢~，title我是全局设置里设置的，应该是没有这个方法吧 这个目前没啥影响。设置最大值那个一般体现在移动端和电脑端兼容的情况，譬如手机端设置了宽度90% 在电脑端没有最大值xxxpx的限制 就会显得特别大。

**Comment by 642661520** [comment]
> 手机端了，谢谢~，标题我是国外设置的，应该是没有这个原因目前这个没有影响。宽度90% 在电脑端没有视频xxxpx的限制会特别大。

可以测试下0.3.7版本，添加全局配置项title，添加配置项maxarea

**Comment by guigui0326** [comment]
测试可以，牛批plus~

**Comment by guigui0326** [comment]
我测试了下使用this.$layer里写的回调事件是可用的，组件上直接绑定好像无效

**Comment by guigui0326** [comment]
> > 像组件不支持发生事件吗？我测试无法使用的调整事件，官方示例也不会触发
> 
> 因为组件已经修改成vue的事件模式， @success=“function” 文档没有写全，抱歉

嗯嗯 我试过了，可以的 灰常感谢~
